const std = @import("std");

const version = std.SemanticVersion.parse(
    @import("build.zig.zon").version,
) catch unreachable;

pub fn build(b: *std.Build) !void {
    const upstream = b.dependency("nut", .{});
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const common_dir = upstream.path("common");
    const include_dir = upstream.path("include");
    const drivers_dir = upstream.path("drivers");

    const libusb_dep = b.dependency("libusb", .{
        .target = target,
        .optimize = optimize,
        .@"system-libudev" = false,
    });

    const usbhid = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });

    usbhid.addIncludePath(generateNutVersionHeader(b).getDirectory());

    const config_header = createConfigHeaderStep(
        b,
        include_dir.path(b, "config.h.in"),
        target.result,
    );
    usbhid.addIncludePath(config_header.getOutputDir());

    usbhid.addIncludePath(include_dir);
    usbhid.addIncludePath(common_dir);
    usbhid.addCSourceFiles(.{
        .root = drivers_dir,
        .files = usbhid_driver_files,
    });
    usbhid.addCSourceFiles(.{
        .root = common_dir,
        .files = common_src_files,
    });

    usbhid.linkLibrary(libusb_dep.artifact("usb"));

    if (target.result.os.tag == .windows) {
        buildAndLinkLibRegex(b, usbhid);
        usbhid.linkSystemLibrary("Ws2_32", .{});
    }

    const usbhid_exe = b.addExecutable(.{
        .name = "usbhid-ups",
        .root_module = usbhid,
    });
    b.installArtifact(usbhid_exe);
}

fn buildAndLinkLibRegex(b: *std.Build, mod: *std.Build.Module) void {
    if (b.lazyDependency("mingw-regex", .{})) |regex_dep| {
        const regex_mod = b.createModule(.{
            .target = mod.resolved_target,
            .optimize = mod.optimize,
            .link_libc = true,
        });
        regex_mod.addIncludePath(regex_dep.path(""));
        regex_mod.addCSourceFiles(.{
            .root = regex_dep.path(""),
            .files = &.{
                "regex.c",
            },
        });
        const regex_lib = b.addLibrary(.{
            .name = "mingw-regex",
            .root_module = regex_mod,
        });
        regex_lib.installHeader(regex_dep.path("regex.h"), "regex.h");

        mod.linkLibrary(regex_lib);
    }
}

fn createConfigHeaderStep(
    b: *std.Build,
    input_file: std.Build.LazyPath,
    target: std.Target,
) *std.Build.Step.ConfigHeader {
    const is_windows = target.os.tag == .windows;

    const opts = .{
        // default dirs
        .ALTPIDPATH = "/var/state/ups",
        .BINDIR = "/usr/local/ups/bin",
        .CGIPATH = "/usr/local/ups/cgi-bin",
        .CONFPATH = "/usr/local//ups/etc",
        .DRVPATH = "/usr/local/ups/bin",
        .HTMLPATH = "/usr/local/ups/html",
        .LIBDIR = "/usr/local/ups/lib",
        .LIBEXECDIR = "/usr/local/ups/libexec",
        .LT_OBJDIR = ".libs/", // TODO required?
        .NUT_DATADIR = "/usr/local/ups/share",
        .NUT_MANDIR = "/usr/local/ups/share/man",
        .PIDPATH = "/var/run",
        .PREFIX = "/usr/local/ups",
        .SBINDIR = "/usr/local/ups/sbin",
        .STATEPATH = "/var/state/ups",

        // build options (TODO support configuration)
        .LOG_FACILITY = .LOG_DAEMON,
        .CONFIG_FLAGS = "",
        .PORT = 3493,
        .RUN_AS_GROUP = "nobody",
        .RUN_AS_USER = "nobody",
        .WITH_ASCIIDOC = null,
        .WITH_AVAHI = null,
        .WITH_CGI = null,
        .WITH_DEV = null,
        .WITH_DEV_LIBNUTCONF = null,
        .WITH_DOCS = null,
        .WITH_FREEIPMI = null,
        .WITH_GPIO = null,
        .WITH_IPMI = null,
        .WITH_LIBGPIO_VERSION = 0x00000000,
        .WITH_LIBGPIO_VERSION_STR = "0x00000000",
        .WITH_LIBLTDL = null,
        .WITH_LIBPOWERMAN = null,
        .WITH_LIBSYSTEMD = null,
        .WITH_LIBSYSTEMD_INHIBITOR = 0,
        .WITH_LIBUSB_0_1 = 0,
        .WITH_LIBUSB_1_0 = 1,
        .WITH_LINUX_I2C = null,
        .WITH_MODBUS = null,
        .WITH_NEON = null,
        .WITH_NSS = null,
        .WITH_NUTCONF = null,
        .WITH_NUT_MONITOR = null,
        .WITH_NUT_SCANNER = null,
        .WITH_OPENSSL = null,
        .WITH_PYNUT = null,
        .WITH_SERIAL = 1,
        .WITH_SNMP = null,
        .WITH_SNMP_STATIC = null,
        .WITH_SOLARIS_SMF = null,
        .WITH_SSL = null,
        .WITH_UNMAPPED_DATA_POINTS = 0,
        .WITH_USB = 1,
        .WITH_USB_BUSPORT = 0,
        .WITH_WRAP = null,
        ._MINIX = null,
        ._POSIX_1_SOURCE = null,
        ._POSIX_SOURCE = null,
        ._UINT32_T = null,
        ._UINT64_T = null,
        ._UINT8_T = null,
        .__func__ = null,
        .@"inline" = null,
        .int16_t = null,
        .int32_t = null,
        .int64_t = null,
        .int8_t = null,
        .intmax_t = null,
        .size_t = null,
        .socklen_t = null,
        .ssize_t = null,
        .uint16_t = null,
        .uint32_t = null,
        .uint64_t = null,
        .uint8_t = null,
        .uintmax_t = null,

        // build info
        .NUT_NETVERSION = "1.3", // TODO get this from somewhere?
        .NUT_WEBSITE_BASE = "https://www.networkupstools.org/historic/v2.8.3",
        .PACKAGE = "nut",
        .PACKAGE_BUGREPORT = "https://github.com/networkupstools/nut/issues",
        .PACKAGE_NAME = "nut",
        .PACKAGE_STRING = "nut 2.8.3", // TODO get this from somewhere?
        .PACKAGE_TARNAME = "nut",
        .PACKAGE_URL = "https://www.networkupstools.org/historic/v2.8.3/index.html",
        .PACKAGE_VERSION = "2.8.3", // TODO get this from somewhere?
        .TREE_VERSION = "2.8",
        .VERSION = "2.8.3",

        // compiler and build system details
        .AC_APPLE_UNIVERSAL_BUILD = null,
        // TODO generate during the build?
        .CC_VERSION = "clang version 20.1.2 (https://github.com/ziglang/zig-bootstrap de424301411b3a34a8a908d8dca01a1d29f2c6df); Target: x86_64-unknown-windows-gnu; Thread model: posix",
        .CPP_VERSION = "clang version 20.1.2 (https://github.com/ziglang/zig-bootstrap de424301411b3a34a8a908d8dca01a1d29f2c6df); Target: x86_64-unknown-windows-gnu; Thread model: posix",
        .CXX_VERSION = "clang version 20.1.2 (https://github.com/ziglang/zig-bootstrap de424301411b3a34a8a908d8dca01a1d29f2c6df); Target: x86_64-unknown-windows-gnu; Thread model: posix",
        .CXX_NO_MINUS_C_MINUS_O = null,
        .FLEXIBLE_ARRAY_MEMBER = .@"/**/",
        .HAVE_PRAGMAS_FOR_GCC_DIAGNOSTIC_IGNORED_CXX98_COMPAT = 1,
        .HAVE_PRAGMAS_FOR_GCC_DIAGNOSTIC_IGNORED_CXX98_COMPAT_BESIDEFUNC = 1,
        .HAVE_PRAGMAS_FOR_GCC_DIAGNOSTIC_IGNORED_FORMAT_NONLITERAL = 1,
        .HAVE_PRAGMAS_FOR_GCC_DIAGNOSTIC_IGNORED_FORMAT_NONLITERAL_BESIDEFUNC = 1,
        .HAVE_PRAGMAS_FOR_GCC_DIAGNOSTIC_IGNORED_FORMAT_TRUNCATION = 1,
        .HAVE_PRAGMAS_FOR_GCC_DIAGNOSTIC_IGNORED_FORMAT_TRUNCATION_BESIDEFUNC = 1,
        .HAVE_PRAGMAS_FOR_GCC_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE = 1,
        .HAVE_PRAGMAS_FOR_GCC_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE_BESIDEFUNC = 1,
        .HAVE_PRAGMA_CLANG_DIAGNOSTIC_IGNORED_DEPRECATED_DECLARATIONS = null,
        .HAVE_PRAGMA_CLANG_DIAGNOSTIC_IGNORED_DEPRECATED_DECLARATIONS_BESIDEFUNC = null,
        .HAVE_PRAGMA_CLANG_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE_RETURN = null,
        .HAVE_PRAGMA_CLANG_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE_RETURN_BESIDEFUNC = null,
        .HAVE_PRAGMA_CLANG_DIAGNOSTIC_PUSH_POP = 1,
        .HAVE_PRAGMA_CLANG_DIAGNOSTIC_PUSH_POP_BESIDEFUNC = 1,
        .HAVE_PRAGMA_CLANG_DIAGNOSTIC_PUSH_POP_INSIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_ADDRESS = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_ADDRESS_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_ARRAY_BOUNDS = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_ARRAY_BOUNDS_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_ASSIGN_ENUM = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_ASSIGN_ENUM_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_CAST_ALIGN = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_CAST_ALIGN_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_CAST_FUNCTION_TYPE_STRICT = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_CAST_FUNCTION_TYPE_STRICT_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_COVERED_SWITCH_DEFAULT = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_COVERED_SWITCH_DEFAULT_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_CXX98_COMPAT = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_CXX98_COMPAT_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_CXX98_COMPAT_PEDANTIC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_CXX98_COMPAT_PEDANTIC_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_DEPRECATED_DECLARATIONS = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_DEPRECATED_DYNAMIC_EXCEPTION_SPEC_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_EXIT_TIME_DESTRUCTORS = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_EXIT_TIME_DESTRUCTORS_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_EXTRA_SEMI_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_EXTRA_SEMI_STMT = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_EXTRA_SEMI_STMT_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_FORMAT_NONLITERAL = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_FORMAT_NONLITERAL_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_FORMAT_OVERFLOW = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_FORMAT_OVERFLOW_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_FORMAT_SECURITY = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_FORMAT_SECURITY_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_FORMAT_TRUNCATION = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_FORMAT_TRUNCATION_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_GLOBAL_CONSTRUCTORS = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_GLOBAL_CONSTRUCTORS_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_MAYBE_UNINITIALIZED = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_MAYBE_UNINITIALIZED_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_OLD_STYLE_CAST_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_PEDANTIC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_PEDANTIC_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_SIGN_COMPARE = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_SIGN_COMPARE_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_SIGN_CONVERSION = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_SIGN_CONVERSION_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_STRICT_PROTOTYPES = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_STRICT_PROTOTYPES_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_STRINGOP_TRUNCATION = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_STRINGOP_TRUNCATION_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_SUGGEST_DESTRUCTOR_OVERRIDE_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_SUGGEST_OVERRIDE_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TAUTOLOGICAL_COMPARE = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TAUTOLOGICAL_COMPARE_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TAUTOLOGICAL_CONSTANT_OUT_OF_RANGE_COMPARE = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TAUTOLOGICAL_CONSTANT_OUT_OF_RANGE_COMPARE_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TAUTOLOGICAL_TYPE_LIMIT_COMPARE = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TAUTOLOGICAL_TYPE_LIMIT_COMPARE_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TAUTOLOGICAL_UNSIGNED_ZERO_COMPARE = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TAUTOLOGICAL_UNSIGNED_ZERO_COMPARE_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TYPE_LIMITS = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_TYPE_LIMITS_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE_BREAK = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE_BREAK_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE_RETURN = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_UNREACHABLE_CODE_RETURN_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_UNUSED_FUNCTION = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_UNUSED_PARAMETER = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_WEAK_VTABLES_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_ZERO_AS_NULL_POINTER_CONSTANT_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_PUSH_POP = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_PUSH_POP_BESIDEFUNC = 1,
        .HAVE_PRAGMA_GCC_DIAGNOSTIC_PUSH_POP_INSIDEFUNC = 1,
        .HAVE___ATTRIBUTE__ = 1,
        .HAVE___ATTRIBUTE__NORETURN = 1,
        .HAVE___ATTRIBUTE__UNUSED_ARG = 1,
        .HAVE___ATTRIBUTE__UNUSED_FUNC = 1,
        .STDC_HEADERS = 1,
        .TIME_WITH_SYS_TIME = 1,
        ._ALL_SOURCE = 1,
        ._GNU_SOURCE = 1,
        ._POSIX_PTHREAD_SEMANTICS = 1,
        ._TANDEM_SOURCE = 1,
        .__EXTENSIONS__ = 1,

        // target-specific defines
        .CPU_TYPE = @tagName(target.cpu.arch.family()),
        .HAVE_IPHLPAPI_H = defFromBool(is_windows),
        .HAVE_WINDOWS_H = defFromBool(is_windows),
        .HAVE_WINSOCK2_H = defFromBool(is_windows),
        .HAVE_WS2TCPIP_H = defFromBool(is_windows),
        .WINDOWS_SOCKETS = defFromBool(is_windows),
        .HAVE_DECL_LOCALTIME_R = @intFromBool(!is_windows),
        .HAVE_DECL_LOCALTIME_S = @intFromBool(is_windows),
        .HAVE_SETENV = defFromBool(!is_windows),
        .HAVE_SETEUID = defFromBool(!is_windows),
        .HAVE_STRPTIME = defFromBool(!is_windows and !target.abi.isGnu()),
        .HAVE_UNSETENV = defFromBool(!is_windows),
        .WITH_MACOSX = defFromBool(target.os.tag.isDarwin()),
        .WORDS_BIGENDIAN = defFromBool(target.cpu.arch.endian() == .big),

        // TODO: need checking for cross-compilation
        // current values generated by autoconf on mingw64
        .FOUND_BOOLEAN_IMPLEM_STR = null,
        .FOUND_BOOLEAN_TYPE = null,
        .FOUND_BOOLEAN_VALUE_FALSE = null,
        .FOUND_BOOLEAN_VALUE_TRUE = null,
        .FOUND_BOOL_IMPLEM_STR = "number",
        .FOUND_BOOL_TYPE = .bool,
        .FOUND_BOOL_T_IMPLEM_STR = null,
        .FOUND_BOOL_T_TYPE = null,
        .FOUND_BOOL_T_VALUE_FALSE = null,
        .FOUND_BOOL_T_VALUE_TRUE = null,
        .FOUND_BOOL_VALUE_FALSE = .false,
        .FOUND_BOOL_VALUE_TRUE = .true,
        .FOUND__BOOL_IMPLEM_STR = "number",
        .FOUND__BOOL_TYPE = ._Bool,
        .FOUND__BOOL_VALUE_FALSE = .false,
        .FOUND__BOOL_VALUE_TRUE = .true,
        .GETNAMEINFO_TYPE_ARG1 = .@"const struct sockaddr *",
        .GETNAMEINFO_TYPE_ARG2 = .socklen_t,
        .GETNAMEINFO_TYPE_ARG46 = .DWORD, // almost certainly windows-only
        .GETNAMEINFO_TYPE_ARG7 = .int,
        .HAVE_ABS = 1,
        .HAVE_ABS_VAL = null,
        .HAVE_ATEXIT = 1,
        .HAVE_AVAHI_CLIENT_CLIENT_H = null,
        .HAVE_AVAHI_CLIENT_NEW = null,
        .HAVE_AVAHI_COMMON_MALLOC_H = null,
        .HAVE_AVAHI_FREE = null,
        .HAVE_BOOLEAN_IMPLEM_ENUM = null,
        .HAVE_BOOLEAN_IMPLEM_INT = null,
        .HAVE_BOOLEAN_IMPLEM_MACRO = null,
        .HAVE_BOOLEAN_TYPE_CAMELCASE = null,
        .HAVE_BOOLEAN_TYPE_LOWERCASE = null,
        .HAVE_BOOLEAN_TYPE_UPPERCASE = null,
        .HAVE_BOOLEAN_VALUE_CAMELCASE = null,
        .HAVE_BOOLEAN_VALUE_LOWERCASE = null,
        .HAVE_BOOLEAN_VALUE_UPPERCASE = null,
        .HAVE_BOOL_IMPLEM_ENUM = null,
        .HAVE_BOOL_IMPLEM_INT = 1,
        .HAVE_BOOL_IMPLEM_MACRO = null,
        .HAVE_BOOL_TYPE_CAMELCASE = null,
        .HAVE_BOOL_TYPE_LOWERCASE = 1,
        .HAVE_BOOL_TYPE_UPPERCASE = null,
        .HAVE_BOOL_T_IMPLEM_ENUM = null,
        .HAVE_BOOL_T_IMPLEM_INT = null,
        .HAVE_BOOL_T_IMPLEM_MACRO = null,
        .HAVE_BOOL_T_TYPE_CAMELCASE = null,
        .HAVE_BOOL_T_TYPE_LOWERCASE = null,
        .HAVE_BOOL_T_TYPE_UPPERCASE = null,
        .HAVE_BOOL_T_VALUE_CAMELCASE = null,
        .HAVE_BOOL_T_VALUE_LOWERCASE = null,
        .HAVE_BOOL_T_VALUE_UPPERCASE = null,
        .HAVE_BOOL_VALUE_CAMELCASE = null,
        .HAVE_BOOL_VALUE_LOWERCASE = 1,
        .HAVE_BOOL_VALUE_UPPERCASE = null,
        .HAVE_CFSETISPEED = null,
        .HAVE_CLOCK_GETTIME = 1,
        .HAVE_CLOCK_MONOTONIC = 1,
        .HAVE_CPPUNIT = null, // TODO: support tests?
        .HAVE_CSTDBOOL = null,
        .HAVE_CXX11 = 1,
        .HAVE_C_VARARRAYS = 1,
        .HAVE_DECL_FABS = 1,
        .HAVE_DECL_FABSF = 1,
        .HAVE_DECL_FABSL = 1,
        .HAVE_DECL_GMTIME_R = 0,
        .HAVE_DECL_GMTIME_S = 1,
        .HAVE_DECL_I2C_SMBUS_ACCESS = null,
        .HAVE_DECL_I2C_SMBUS_READ_BLOCK_DATA = null,
        .HAVE_DECL_I2C_SMBUS_READ_BYTE_DATA = null,
        .HAVE_DECL_I2C_SMBUS_READ_WORD_DATA = null,
        .HAVE_DECL_I2C_SMBUS_WRITE_BYTE_DATA = null,
        .HAVE_DECL_I2C_SMBUS_WRITE_WORD_DATA = null,
        .HAVE_DECL_LOG_UPTO = 0,
        .HAVE_DECL_OPTIND = 1,
        .HAVE_DECL_POW10 = 0,
        .HAVE_DECL_REALPATH = 0,
        .HAVE_DECL_REGCOMP = 1, // TODO: make regex support optional?
        .HAVE_DECL_REGEXEC = 1,
        .HAVE_DECL_ROUND = 1,
        .HAVE_DECL_TIMEGM = 0,
        .HAVE_DECL_UU_LOCK = 0,
        .HAVE_DECL__MKGMTIME = 1,
        .HAVE_DECL___FUNCTION__ = null,
        .HAVE_DECL___FUNC__ = 1,
        .HAVE_DLFCN_H = null,
        .HAVE_DUP = 1,
        .HAVE_DUP2 = 1,
        .HAVE_FCNTL_H = 1,
        .HAVE_FCVT = 1,
        .HAVE_FCVTL = null,
        .HAVE_FILENO = 1,
        .HAVE_FLOAT_H = 1,
        .HAVE_FLOCK = null,
        .HAVE_FREEIPMI = null,
        .HAVE_FREEIPMI_11X_12X = null,
        .HAVE_FREEIPMI_FREEIPMI_H = null,
        .HAVE_FREEIPMI_MONITORING = null,
        .HAVE_GDFONTMB_H = null,
        .HAVE_GD_H = null,
        .HAVE_GETADAPTERSADDRESSES = null,
        .HAVE_GETADAPTERSINFO = 1,
        .HAVE_GETIFADDRS = null,
        .HAVE_GETOPT_H = 1,
        .HAVE_GETOPT_LONG = 1,
        .HAVE_GETPASSPHRASE = null,
        .HAVE_GMTIME_R = null,
        .HAVE_GMTIME_S = null,
        .HAVE_GPIOD_CHIP_CLOSE = null,
        .HAVE_GPIOD_CHIP_OPEN = null,
        .HAVE_GPIOD_CHIP_OPEN_BY_NAME = null,
        .HAVE_GPIOD_H = null,
        .HAVE_IFADDRS_H = null,
        .HAVE_INET_NTOP = 1,
        .HAVE_INET_PTON = 1,
        .HAVE_INIT_SNMP = null, // TODO: support net-snmp
        .HAVE_INTMAX_T = 1,
        .HAVE_INTTYPES_H = 1,
        .HAVE_IPMI_MONITORING_H = null,
        .HAVE_LIBGD = null,
        .HAVE_LIBLTDL = null,
        .HAVE_LIBPOWERMAN_H = null,
        .HAVE_LIBREGEX = 1,
        .HAVE_LIBUSB_DETACH_KERNEL_DRIVER = null, // TODO: support libusb kernel driver?
        .HAVE_LIBUSB_DETACH_KERNEL_DRIVER_NP = null,
        .HAVE_LIBUSB_GET_PORT_NUMBER = 1, // TODO: make libusb support optional?
        .HAVE_LIBUSB_H = 1,
        .HAVE_LIBUSB_INIT = 1,
        .HAVE_LIBUSB_KERNEL_DRIVER_ACTIVE = null,
        .HAVE_LIBUSB_SET_AUTO_DETACH_KERNEL_DRIVER = null,
        .HAVE_LIBUSB_STRERROR = 1,
        .HAVE_LIB_BSD_KVM_PROC = null,
        .HAVE_LIB_ILLUMOS_PROC = null,
        .HAVE_LIMITS_H = 1,
        .HAVE_LINUX_I2C_DEV_H = null,
        .HAVE_LINUX_SERIAL_H = null,
        .HAVE_LINUX_SMBUS_H = null,
        .HAVE_LOCALTIME_R = null,
        .HAVE_LOCALTIME_S = null,
        .HAVE_LOCKF = null,
        .HAVE_LONG_DOUBLE = null,
        .HAVE_LONG_LONG_INT = 1,
        .HAVE_LTDL_H = null,
        .HAVE_LUSB0_USB_H = null, // TODO: support libusb-0.1?
        .HAVE_MATH_H = 1,
        .HAVE_MEMORY_H = 1,
        .HAVE_MODBUS_H = null, // TODO support modbus?
        .HAVE_MODBUS_NEW_RTU = null,
        .HAVE_MODBUS_NEW_RTU_USB = null,
        .HAVE_MODBUS_NEW_TCP = null,
        .HAVE_MODBUS_SET_BYTE_TIMEOUT = null,
        .HAVE_MODBUS_SET_RESPONSE_TIMEOUT = null,
        .HAVE_NETDB_H = null,
        .HAVE_NETINET_IN_H = null,
        .HAVE_NET_IF_H = null,
        .HAVE_NET_SNMP_NET_SNMP_CONFIG_H = null,
        .HAVE_NET_SNMP_NET_SNMP_INCLUDES_H = null,
        .HAVE_NE_SET_CONNECT_TIMEOUT = null,
        .HAVE_NE_SOCK_CONNECT_TIMEOUT = null,
        .HAVE_NE_XMLREQ_H = null,
        .HAVE_NE_XML_DISPATCH_REQUEST = null,
        .HAVE_NSS_H = null,
        .HAVE_NSS_INIT = null,
        .HAVE_ON_EXIT = null,
        .HAVE_OPENSSL_SSL_H = null,
        .HAVE_PM_CONNECT = null,
        .HAVE_POLL_H = null,
        .HAVE_PTHREAD = 1,
        .HAVE_PTHREAD_TRYJOIN = null,
        .HAVE_READLINK = null,
        .HAVE_REGEX_H = 1,
        .HAVE_SD_BOOTED = null,
        .HAVE_SD_BUS_CALL_METHOD = null,
        .HAVE_SD_BUS_DEFAULT_SYSTEM = null,
        .HAVE_SD_BUS_ERROR_FREE = null,
        .HAVE_SD_BUS_FLUSH_CLOSE_UNREF = null,
        .HAVE_SD_BUS_GET_PROPERTY_TRIVIAL = null,
        .HAVE_SD_BUS_MESSAGE_READ_BASIC = null,
        .HAVE_SD_BUS_MESSAGE_UNREF = null,
        .HAVE_SD_BUS_OPEN_SYSTEM = null,
        .HAVE_SD_BUS_OPEN_SYSTEM_WITH_DESCRIPTION = null,
        .HAVE_SD_BUS_SET_DESCRIPTION = null,
        .HAVE_SD_NOTIFY = null,
        .HAVE_SD_NOTIFY_BARRIER = null,
        .HAVE_SD_WATCHDOG_ENABLED = null,
        .HAVE_SEMAPHORE_H = 1,
        .HAVE_SEMAPHORE_NAMED = 1,
        .HAVE_SEMAPHORE_UNNAMED = 1,
        .HAVE_SETLOGMASK = null,
        .HAVE_SETSID = null,
        .HAVE_SIGACTION = null,
        .HAVE_SIGEMPTYSET = null,
        .HAVE_SIGNAL_H = 1,
        .HAVE_SNPRINTF = 1,
        .HAVE_SSL_CTX_NEW = null,
        .HAVE_SSL_H = null,
        .HAVE_STDARG_H = 1,
        .HAVE_STDBOOL_H = 1,
        .HAVE_STDINT_H = 1,
        .HAVE_STDLIB_H = 1,
        .HAVE_STRCASECMP = 1,
        .HAVE_STRCASESTR = null,
        .HAVE_STRDUP = 1,
        .HAVE_STRERROR = 1,
        .HAVE_STRINGS_H = 1,
        .HAVE_STRING_H = 1,
        .HAVE_STRLWR = 1,
        .HAVE_STRNCASECMP = 1,
        .HAVE_STRNLEN = 1,
        .HAVE_STRSEP = null,
        .HAVE_STRSTR = 1,
        .HAVE_STRTOF = 1,
        .HAVE_STRTOK_R = 1,
        .HAVE_STRUCT_POLLFD = 1,
        .HAVE_SUSECONDS_T = null,
        .HAVE_SYSTEMD = null,
        .HAVE_SYSTEMD_SD_BUS_H = null,
        .HAVE_SYSTEMD_SD_DAEMON_H = null,
        .HAVE_SYS_MODEM_H = null,
        .HAVE_SYS_RESOURCE_H = null,
        .HAVE_SYS_SELECT_H = null,
        .HAVE_SYS_SIGNAL_H = null,
        .HAVE_SYS_SOCKET_H = null,
        .HAVE_SYS_STAT_H = 1,
        .HAVE_SYS_TERMIOS_H = null,
        .HAVE_SYS_TIME_H = 1,
        .HAVE_SYS_TYPES_H = 1,
        .HAVE_TCPD_H = null,
        .HAVE_TCSENDBREAK = null,
        .HAVE_TERMIOS_H = null,
        .HAVE_TIMEGM = null,
        .HAVE_TIME_H = 1,
        .HAVE_UINTMAX_T = 1,
        .HAVE_UNISTD_H = 1,
        .HAVE_UNSIGNED_LONG_LONG_INT = 1,
        .HAVE_USB_DETACH_KERNEL_DRIVER_NP = null,
        .HAVE_USB_H = null,
        .HAVE_USB_INIT = null,
        .HAVE_USECONDS_T = 1,
        .HAVE_USLEEP = 1,
        .HAVE_UU_LOCK = null,
        .HAVE_VARARGS_H = null,
        .HAVE_VSNPRINTF = 1,
        .HAVE_WRAP = null,
        .HAVE__BOOL_IMPLEM_ENUM = null,
        .HAVE__BOOL_IMPLEM_INT = 1,
        .HAVE__BOOL_IMPLEM_MACRO = null,
        .HAVE__BOOL_TYPE_CAMELCASE = 1,
        .HAVE__BOOL_TYPE_LOWERCASE = null,
        .HAVE__BOOL_TYPE_UPPERCASE = null,
        .HAVE__BOOL_VALUE_CAMELCASE = null,
        .HAVE__BOOL_VALUE_LOWERCASE = 1,
        .HAVE__BOOL_VALUE_UPPERCASE = null,
        .HAVE__MKGMTIME = 1,
        .MAN_SECTION_API = "3",
        .MAN_SECTION_API_BASE = "3",
        .MAN_SECTION_CFG = "5",
        .MAN_SECTION_CFG_BASE = "5",
        .MAN_SECTION_CMD_SYS = "8",
        .MAN_SECTION_CMD_SYS_BASE = "8",
        .MAN_SECTION_CMD_USR = "1",
        .MAN_SECTION_CMD_USR_BASE = "1",
        .NEED_GETOPT_DECLS = null,
        .NEED_GETOPT_H = 1,
        .NUT_HAVE_LIBNETSNMP_DRAFT_BLUMENTHAL_AES_04 = null,
        .NUT_HAVE_LIBNETSNMP_usmAES128PrivProtocol = null,
        .NUT_HAVE_LIBNETSNMP_usmAES192PrivProtocol = null,
        .NUT_HAVE_LIBNETSNMP_usmAES256PrivProtocol = null,
        .NUT_HAVE_LIBNETSNMP_usmAESPrivProtocol = null,
        .NUT_HAVE_LIBNETSNMP_usmDESPrivProtocol = null,
        .NUT_HAVE_LIBNETSNMP_usmHMAC192SHA256AuthProtocol = null,
        .NUT_HAVE_LIBNETSNMP_usmHMAC256SHA384AuthProtocol = null,
        .NUT_HAVE_LIBNETSNMP_usmHMAC384SHA512AuthProtocol = null,
        .NUT_HAVE_LIBNETSNMP_usmHMACMD5AuthProtocol = null,
        .NUT_HAVE_LIBNETSNMP_usmHMACSHA1AuthProtocol = null,
        .NUT_MODBUS_HAS_USB = null,
        .NUT_MODBUS_LINKTYPE_STR = null,
        .NUT_MODBUS_TIMEOUT_ARG_sec_usec_uint32 = null,
        .NUT_MODBUS_TIMEOUT_ARG_sec_usec_uint32_cast_timeval_fields = null,
        .NUT_MODBUS_TIMEOUT_ARG_timeval = null,
        .NUT_MODBUS_TIMEOUT_ARG_timeval_numeric_fields = null,
        .REQUIRE_NUT_STRARG = 1,
        .SIZEOF_VOID_P = 8,
        .SUN_LIBUSB = null,
        .WANT_TIMEGM_FALLBACK = null,

        // details of the build env (not required)
        .ABS_TOP_BUILDDIR = null,
        .ABS_TOP_SRCDIR = null,
        .AUTOTOOLS_BUILD_ALIAS = null,
        .AUTOTOOLS_BUILD_SHORT_ALIAS = null,
        .AUTOTOOLS_HOST_ALIAS = null,
        .AUTOTOOLS_HOST_SHORT_ALIAS = null,
        .AUTOTOOLS_TARGET_ALIAS = null,
        .AUTOTOOLS_TARGET_SHORT_ALIAS = null,
        .CCACHE_NAMESPACE = null,
        .MULTIARCH_TARGET_ALIAS = null,
        .SOFILE_LIBAVAHI = null,
        .SOFILE_LIBFREEIPMI = null,
        .SOFILE_LIBNEON = null,
        .SOFILE_LIBNETSNMP = null,
        .SOFILE_LIBUSB0 = null,
        .SOFILE_LIBUSB1 = null,
        .SOPATH_LIBAVAHI = null,
        .SOPATH_LIBFREEIPMI = null,
        .SOPATH_LIBNEON = null,
        .SOPATH_LIBNETSNMP = null,
        .SOPATH_LIBUSB0 = null,
        .SOPATH_LIBUSB1 = null,
    };

    return b.addConfigHeader(
        .{ .style = .{ .autoconf_undef = input_file } },
        opts,
    );
}

fn defFromBool(val: bool) ?u1 {
    return if (val) 1 else null;
}

fn generateNutVersionHeader(b: *std.Build) *std.Build.Step.WriteFile {
    var buf: [200]u8 = undefined;
    const data = std.fmt.bufPrint(
        &buf,
        \\#define NUT_VERSION_MACRO "{f}"
        \\#define NUT_VERSION_SEMVER_MACRO "{f}"
        \\#define NUT_VERSION_IS_RELEASE 1
        \\#define NUT_VERSION_IS_PRERELEASE 0
    ,
        .{ version, version },
    ) catch unreachable;
    return b.addWriteFile("nut_version.h", data);
}

const usbhid_driver_files: []const []const u8 = &.{
    "apc-hid.c",
    "arduino-hid.c",
    "belkin-hid.c",
    "cps-hid.c",
    "explore-hid.c",
    "liebert-hid.c",
    "mge-hid.c",
    "powercom-hid.c",
    "tripplite-hid.c",
    "idowell-hid.c",
    "openups-hid.c",
    "powervar-hid.c",
    "delta_ups-hid.c",
    "ecoflow-hid.c",
    "ever-hid.c",
    "legrand-hid.c",
    "salicru-hid.c",
    "usbhid-ups.c",

    "dstate.c",
    "upsdrvquery.c",
    "libhid.c",
    "libusb1.c",
    "hidparser.c",
    "usb-common.c",

    "main.c",
};

const common_src_files: []const []const u8 = &.{
    "common.c",
    "parseconf.c",
    "upsconf.c",
    "state.c",
    "str.c",
    "setenv.c",
    "wincompat.c",
};
